### ISSUE TITLE
Create an api for the metropolitan statistical areas for frontloading UI

### ISSUE THREAD

**Issue by rameshnatarajanus** [SM24-Industrial-Software-Dev/ML-forecasting-NOx-levels#12]
Create an API to support the UI requirements for metropolitan statistical areas (MSA's). 

This api should support at a minimum providing a list of metropolitian areas.

In addition, it can provide  metadata for dropdown search from the UI, and also creating a map based interface for selecting MSA's for plotting and forecasting.

**Comment by EStein-Projects** [comment]
Reminder to myself that both all and some options should be available
