### ISSUE TITLE
Bring in mobility data from covid 19 period

### ISSUE THREAD

**Issue by rameshnatarajanus** [SM24-Industrial-Software-Dev/ML-forecasting-NOx-levels#24]
This website provides mobility data which will impact Nox emissions from the Google[ link](https://www.google.com/covid19/mobility/data_documentation.html?hl=en).

Examine data to extract daily time series for ML forecasting

**Comment by EStein-Projects** [comment]
See this [Apple report](https://machinelearning.apple.com/research/modeling-covid-mobility) that uses data obtained from Google's mobility trends.

**Comment by rameshnatarajanus** [comment]
@RimazeiHamachshav - so the Apple data uses the [Google mobility trends](https://www.google.com/covid19/mobility/) data.  We might as well stick to the original which is unfortunately at the state level (and so too coarse-grined) even if it daily data (so have the right resolution in time)

**Comment by rameshnatarajanus** [comment]
Check out this github site 

https://github.com/NINAnor/covid19-air-pollution/blob/master/DATA/Misc/Global_Mobility_Report.csv
