### ISSUE TITLE
Only have one authentication for all GEE api calls

### ISSUE THREAD

**Issue by APoulad** [SM24-Industrial-Software-Dev/ML-forecasting-NOx-levels#26]
The GEE authentication should be performed only once in a session.  All subsequent api calls (for uploading shape files, multiple regions etc.) should not require re-authetication)

**Comment by rameshnatarajanus** [comment]
@oricb1 - do you have any progress on this issue?

**Comment by rameshnatarajanus** [comment]
1. Is it possible to test if already authenticated and skip authentication (for each new library API call). 
2. How to avoid pop-ups requesting confirmation of secrets uploading etc.

**Comment by rameshnatarajanus** [comment]
Getting the VM instance to work and connect to for testing
