### ISSUE TITLE
Design API for recovering data from Google Earth Engine

### ISSUE THREAD

**Issue by rameshnatarajanus** [SM24-Industrial-Software-Dev/ML-forecasting-NOx-levels#4]
Design and implement a simple API for taking the input selections from the UI (input geometries of MSA's or metropolitan service areas, and date ranges for the analysis, e.g. start and end dates) and returning the output (time series of mean NO2 concentrations over these geometries) as a pandas dataframe.

The design will closely follow the version in [this colab cell](https://colab.research.google.com/drive/1lynJQIThuq98t8SZOvw09C6c8lF2-msd#scrollTo=VAzcOj5vMb0P&line=5&uniqifier=1)

To avoid being blocked by the generation of the geometries for MSA's initially just use the geometry of the level 3 admin boundary as provided by the 'FAO/GAUL_SIMPLIFIED_500m/2015/level2' dataset in google earth engine.

After implementing this simple API, you should first create an design document addressing the following issues

- what is the requirement of this API (function call and return signatures, and how these fit into the overall application design)
- What is the format of the  inputs and outputs for any server side processing
- What are the latency requirements of executing this API  in view of the UI responsiveness
- Would any preprocessing be beneficial for reducing application latency.
- What is the memory requirement on the client for storing the output tables

**Comment by APoulad** [comment]
@oricb1 Your current API does not take geometries as an input. This needs to be changed for me to continue working on the Dash application.

**Comment by APoulad** [comment]
@rameshnatarajanus 
> To avoid being blocked by the generation of the geometries for MSA's initially just use the geometry of the level 3 admin boundary as provided by the 'FAO/GAUL_SIMPLIFIED_500m/2015/level2' dataset in google earth engine.

I don't see any such dataset. There only exists a level0, level1, and level2 boundary. 

Instead I believe it's possible to not utilize the dataset at all and only use the MSA geometries
